### ISSUE TITLE
Milestone: Trong tháng 2 revise xong chương Preliminaries

### ISSUE THREAD

**Issue by tiepvupsu** [aivivn/d2l-vn#460]
* [ ] 2.1. Thao tác với Dữ liệu
* [x] 2.2. Tiền Xử lý Dữ liệu
* [x] 2.3. Đại số Tuyến tính
* [x] 2.4. Giải tích
* [x] 2.5. Tính vi phân Tự động
* [x] 2.6. Xác suất
* [x] 2.7. Tài liệu

**Comment by tiepvupsu** [comment]
Làm thế nào pin được issue này lên đầu nhỉ @duythanhvn

**Comment by duythanhvn** [comment]
Em đã pin lên ạ. Nằm ở góc dưới bên phải nè anh.

<img width="167" alt="Screen Shot 2020-02-03 at 01 02 05" src="https://user-images.githubusercontent.com/8481767/73612736-cc609180-4620-11ea-8231-53824c24873c.png">

**Comment by tiepvupsu** [comment]
Oh, nhanh vãi. Hôm nay em trực trên này luôn à :)).

**Comment by duythanhvn** [comment]
:))) nằm vùng anh ạ.

**Comment by lkhphuc** [comment]
Đang loay hoay review PR kia thì thấy merge luôn :)). Hờn đi dịch chương khác.

**Comment by tiepvupsu** [comment]
Dạo này @duythanhvn có vẻ merge hơi mạnh tay, cẩn thận về sau revise lại ăn đủ.

**Comment by tiepvupsu** [comment]
> Đang loay hoay review PR kia thì thấy merge luôn :)). Hờn đi dịch chương khác.

Chắc giờ mình quy định với nhau là có 2 approvals mới cho merge nhỉ. Để anh xe có force được không.

**Comment by tiepvupsu** [comment]
Done 
![image](https://user-images.githubusercontent.com/2201237/73613759-a057f880-45ad-11ea-908d-2cef9f6b1b20.png)

**Comment by duythanhvn** [comment]
Còn 14 phần cần nhận dịch nữa là chúng ta tiến vào giai đoạn revise. Anh em chiến thôi!!!
